[Model]
model_name = "model_1"
num_encoding_blocks=4
out_channels_first_layer=16
upsampling_type= 'conv'
num_classes = 4
num_epochs = 100
batch_size = 16
num_workers = 8
save = true
save_best= true

[ROI]
extract_ROI = false #If true, must specify padding_size and crop_size
padding_size = 10
crop_size = 128

[Spatial]


RandomFlip.probability = 0.5
RandomFlip.flip_probability = 1
RandomFlip.axes = 1 #(0,1,2)

RandomAffine.probability = 0.5
RandomAffine.scales = 0.9
RandomAffine.translation = 10 #in mm
RandomAffine.isotropic = false
RandomAffine.center = 'image' #'image'
 
#RandomElasticDeformation.#probability = 0.25
#RandomElasticDeformation.#num_control_points = 5



#[Intensity]
    [Motion]
    probability = 0.25
    degrees = 5
    translation = 2
    num_transforms = 1

    [BiasField]
    probability = 0.25
    std = 0.2

    [Noise]
    probability = 0.25
    mean = 0
    std = 0.25

    [Gamma]
    probability = 0.25
    log_gamma = 0.3

    
